version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes: 
      - db_data:/var/lib/postgresql/data/
    env_file: 
      - ./.env
 
  backend:
    image: seerez/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env 

  frontend:
    image: seerez/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
 
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - backend
 
volumes:
  static_value:
  media_value:
  db_data:
